# Generated by Django 5.1.7 on 2025-05-12 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='description',
        ),
    ]
