# Generated by Django 5.2.1 on 2025-06-04 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_table_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='qr_code_image',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/'),
        ),
    ]
